[package]
name    = "reclaim-gui"
version.workspace = true
edition.workspace = true

[[bin]]
name = "reclaim-gui"
path = "src/main.rs"

[dependencies]
reclaim-core = { path = "../reclaim-core" }
anyhow.workspace  = true
chrono.workspace  = true
egui.workspace    = true
eframe.workspace  = true
dirs.workspace    = true
crossbeam-channel = "0.5"
serde_json.workspace = true
